import type { Model, Types } from 'mongoose';

/**
 * Shared helpers for the admin controllers.
 */

/**
 * Returns a slug that is unique within `model`'s collection, appending `-2`,
 * `-3`, ... on collision. `excludeId` lets an update keep its own slug without
 * colliding with itself.
 *
 * Slugs are required on Product and Category but not auto-generated by a model
 * hook, so the admin write path owns this.
 */
export async function uniqueSlug(
  model: Pick<Model<{ slug: string }>, 'exists'>,
  base: string,
  excludeId?: Types.ObjectId,
): Promise<string> {
  const root = base || 'item';
  let candidate = root;
  let n = 2;
  // Bounded loop: in practice one or two iterations; the guard stops a runaway.
  for (let attempts = 0; attempts < 100; attempts += 1) {
    const clash = await model.exists({
      slug: candidate,
      ...(excludeId ? { _id: { $ne: excludeId } } : {}),
    });
    if (!clash) return candidate;
    candidate = `${root}-${n}`;
    n += 1;
  }
  // Extremely unlikely fallback: suffix with a timestamp-free counter ceiling.
  return `${root}-${Date.now().toString(36)}`;
}
